### ISSUE TITLE
Relative urls don't work properly

### ISSUE THREAD

**Issue by oscarotero** [binyamin/deno-sass#4]
Hi, I just detected a bug in Lume using your `deno-sass` library in the Lume Sass plugin.

Let's say we have this file structure:

```
styles.scss
_includes/
    |_ main.scss
    |_ colors.scss
```

The `styles.scss` loads the main.scss file:

```scss
@import 'main.scss';
```

This works fine, it's resolved to `_includes/main.scss` (althought the `@import '/main.scss';`, with `/`, doesn't work, not sure if this is a bug).

The file `_includes/main.scss` has this content:

```scss
@import './colors.scss';
```

And this url is not resolved from the `_includes/main.scss` file, but the initial file, which throws an error.

**Comment by binyamin** [comment]
Are you referring to [the gitlab repository](https://gitlab.com/binyamin/deno-sass)? This repository was my first attempt, and it's buggy. I should probably archive it.

By the way, I'm using GitLab for the module since it seems less popular than GitHub. I don't want to be the only one responsible for Deno's only feature-complete dart-sass module.

**Comment by oscarotero** [comment]
Yes, sorry, you're right. I just pasted this issue in the gitlab repo so we can continue the discussion there.
Closing this :)
